# Form implementation generated from reading ui file 'EditProperties.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.Submit = QtWidgets.QPushButton(parent=Form)
        self.Submit.setObjectName("Submit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.Submit)
        self.descard_button = QtWidgets.QPushButton(parent=Form)
        self.descard_button.setObjectName("descard_button")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.descard_button)
        self.name_label = QtWidgets.QLabel(parent=Form)
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.name_label)
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEdit)
        self.desc_edit = QtWidgets.QLineEdit(parent=Form)
        self.desc_edit.setObjectName("desc_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.desc_edit)
        self.keybinding_edit = QtWidgets.QLineEdit(parent=Form)
        self.keybinding_edit.setObjectName("keybinding_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.keybinding_edit)
        self.cmd_edit = QtWidgets.QLineEdit(parent=Form)
        self.cmd_edit.setObjectName("cmd_edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cmd_edit)
        self.dependency_edit = QtWidgets.QLineEdit(parent=Form)
        self.dependency_edit.setObjectName("dependency_edit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dependency_edit)
        self.script_path_edit = QtWidgets.QLineEdit(parent=Form)
        self.script_path_edit.setObjectName("script_path_edit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.script_path_edit)
        self.desc_edit_label = QtWidgets.QLabel(parent=Form)
        self.desc_edit_label.setObjectName("desc_edit_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.desc_edit_label)
        self.keybinding_label = QtWidgets.QLabel(parent=Form)
        self.keybinding_label.setObjectName("keybinding_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.keybinding_label)
        self.cmd_label = QtWidgets.QLabel(parent=Form)
        self.cmd_label.setObjectName("cmd_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.cmd_label)
        self.dependency_label = QtWidgets.QLabel(parent=Form)
        self.dependency_label.setObjectName("dependency_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.dependency_label)
        self.script_path_label = QtWidgets.QLabel(parent=Form)
        self.script_path_label.setObjectName("script_path_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.script_path_label)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Submit.setText(_translate("Form", "Submit"))
        self.descard_button.setText(_translate("Form", "Discard"))
        self.name_label.setText(_translate("Form", "Name"))
        self.desc_edit_label.setText(_translate("Form", "Description"))
        self.keybinding_label.setText(_translate("Form", "Keybinding"))
        self.cmd_label.setText(_translate("Form", "Command"))
        self.dependency_label.setText(_translate("Form", "Dependency"))
        self.script_path_label.setText(_translate("Form", "script path"))
